name: insulin95
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  awesome_dialog: ^3.2.1
  bloc: ^9.0.0
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.8
  dash_chat_2: ^0.0.21
  dots_indicator: ^4.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.3.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  lottie: ^3.3.1
  page_transition: ^2.2.1
  shared_preferences: 2.5.3
  skeletonizer: ^2.1.0+1
  timezone: ^0.10.1
  water_drop_nav_bar: ^2.2.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/main_images/
    - assets/on_board/
    - assets/logos/
    - assets/home/
    - assets/icons/
    - assets/test_images/
    - assets/animations/
