// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8qkYeM9ZIryCD_zgcwBBRgUDkYFdPBY',
    appId: '1:76757401402:web:8574e4eaa6a4859a9d1a03',
    messagingSenderId: '76757401402',
    projectId: 'insuline95-6551c',
    authDomain: 'insuline95-6551c.firebaseapp.com',
    storageBucket: 'insuline95-6551c.firebasestorage.app',
    measurementId: 'G-T08T327N2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqhtnv8bQ2Vo4dSuYB3O7u7rvghnt_I58',
    appId: '1:76757401402:android:36eacd4e861b052d9d1a03',
    messagingSenderId: '76757401402',
    projectId: 'insuline95-6551c',
    storageBucket: 'insuline95-6551c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzHNFwIR0RANI23D79IeO0ScTLNLa6yEc',
    appId: '1:76757401402:ios:2567eb10371acfa19d1a03',
    messagingSenderId: '76757401402',
    projectId: 'insuline95-6551c',
    storageBucket: 'insuline95-6551c.firebasestorage.app',
    iosBundleId: 'com.example.insulin95',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR8qkYeM9ZIryCD_zgcwBBRgUDkYFdPBY',
    appId: '1:76757401402:web:357791eebafd4a559d1a03',
    messagingSenderId: '76757401402',
    projectId: 'insuline95-6551c',
    authDomain: 'insuline95-6551c.firebaseapp.com',
    storageBucket: 'insuline95-6551c.firebasestorage.app',
    measurementId: 'G-KQ01KZ218N',
  );
}
